-- =============================================================================
-- Quarity — Schéma OLTP PostgreSQL : DÉPLACÉ
-- =============================================================================
-- Source de vérité du schéma = back/migrations/ (migrations sqlx, appliquées
-- automatiquement par le back au démarrage — cf. back/src/main.rs).
--   * back/migrations/0001_init.sql : schéma initial gelé (23 tables, idempotent)
--   * toute évolution = nouvelle migration back/migrations/000N_*.sql
--
-- Ce fichier est conservé comme POINTEUR pour ne pas casser les références
-- documentaires existantes (docs/data-model.md, logs/…). Ne plus y mettre de DDL.
-- Le seed de démonstration reste dans db/sql/02_seed.sql
-- (lancement : `docker compose --profile seed run --rm seed`).
-- =============================================================================
